### ISSUE TITLE
Hello, there are some errors in the code.

### ISSUE THREAD

**Issue by sui0528** [sdcondon/SCFirstOrderLogic#1]
Hello, thank you for your code sharing, I think it will be very helpful for me.
But I found some errors in the code:
SentenceParser.cs(114,79): error CS0246: The type or namespace name 'FirstOrderLogicParser' could not be found (are you missing a using directive or an assembly reference?)
SentenceParser.cs(74,48): error CS0246: The type or namespace name 'FirstOrderLogicBaseVisitor<>' could not be found (are you missing a using directive or an assembly reference?)
SentenceParser.cs(3,42): error CS0234: The type or namespace name 'Antlr' does not exist in the namespace 'SCFirstOrderLogic.SentenceCreation' (are you missing an assembly reference?)

Also, the FirstOrderLogicLexer is not found.

**Comment by sdcondon** [comment]
Hello! No problem!

So, what appears to have gone wrong here is that ANTLR has failed to generate some source code from the grammar file in the solution. What is *supposed* to happen is that a target added by the Antlr4BuildTasks NuGet package processes the FirstOrderLogic.g4 file (in SentenceCreation) to output the source code for the classes you mention here. Then they get compiled along with everything else - ultimately giving you the `SentenceParser.Parse("∀ x, ..")` functionality.

I have explicitly excluded these generated files from the repo (see the top of the .gitignore file) because they shouldn't *need* to be checked in - the grammar file and the ANTLR setup in the project file should suffice for them to be generated for you whenever you build. If I need to, I suppose I could be persuaded to add them to the repo so that it doesn't matter if the ANTLR build task isn't working for you - but of course this wouldn't help anyone who wants to play with the grammar definition - so it's not my preferred solution.

Could I possibly ask you for some more information? I'm looking for any errors that the ANTLR build task produced in the build output. I can give in-depth instructions if you need them, but, if you are using build output verbosity of at least "normal", very early in your build output you should see a line that reads `1>Target Antlr4Compile:`. Below that, there will be output from it trying to generate these classes. I strongly suspect that you will see some errors here.

As mentioned in the README, ANTLR is ultimately a Java tool - so it might need to download an instance of the "Java Runtime Environment" in order to run it. My initial guess is that something is going wrong with that - an access failure or somesuch. To be clear, what this will help me decide is if I can just add some more content to the readme to help people like you get ANTLR working, or if I should just add the latest generated files to the repo (which as mentioned above, is not a "complete" solution).

**Comment by sdcondon** [comment]
Hmm. Actually, I've just been experimenting with this and noticed something..

If you do a full rebuild (i.e. "Rebuild" instead of "Build" if you're using VS, or include "--no-incremental" if you're using the CLI), does it work then?

**Comment by sui0528** [comment]
Oh, I think I got it. Thank you for your fast reply.
I just use the code in one of my Unity (a game engine) projects, so I don't open the solution but just copy the code to the Unity project folder.
I am not familiar with ANTLR, I am not sure how to use it in Unity.
If you are familiar with Unity, could you offer some advice on getting your code into Unity, if possible?
Thank you so much!

**Comment by sui0528** [comment]
Please forgive me if I don't make myself clear, my English is not good.

**Comment by sui0528** [comment]
Thank you very much, I have solved the problem!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 晚上8:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sdcondon/SCFirstOrderLogic] Hello, there are some errors in the code. (Issue #1)





 
Hmm. Actually, I've just been experimenting with this and noticed something..
 
If you do a full rebuild (i.e. "Rebuild" instead of "Build" if you're using VS, or include "--no-incremental" if you're using the CLI), does it work then?

**Comment by sdcondon** [comment]
Glad to hear it. Good luck, have fun!
